# Generated by Django 5.2.4 on 2025-07-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSGEChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField()),
                ('intitule', models.CharField()),
                ('rubrique', models.CharField()),
                ('chapitre', models.CharField()),
                ('intitule_chapitre', models.CharField()),
                ('intitule_rubrique', models.CharField()),
                ('acronym', models.CharField()),
            ],
        ),
    ]
