# Generated by Django 5.2.4 on 2025-07-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes_nominaux_geneve', '0002_alter_rsgechapter_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rsgechapter',
            table='RSGEChapter',
        ),
    ]
