# Generated by Django 5.2.4 on 2025-08-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes_nominaux_geneve', '0003_alter_rsgechapter_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherVotingsData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('voting_id', models.CharField()),
                ('voting_external_id', models.CharField()),
                ('voting_date', models.CharField()),
                ('voting_affair_external_id', models.CharField()),
                ('voting_affair_number', models.CharField()),
                ('voting_title_fr', models.CharField()),
                ('voting_url_fr', models.CharField()),
                ('voting_results_yes', models.CharField()),
                ('voting_results_no', models.CharField()),
                ('voting_results_abstention', models.CharField()),
                ('voting_affair_title_fr', models.CharField()),
                ('type_vote_label', models.CharField()),
            ],
            options={
                'db_table': 'data_votings_others',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='personsData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('person_external_id', models.CharField()),
                ('person_fullname', models.CharField()),
                ('person_firstname', models.CharField()),
                ('person_lastname', models.CharField()),
                ('person_party_fr', models.CharField()),
                ('person_website_parliament_url_fr', models.CharField()),
                ('person_image_url', models.CharField()),
                ('person_birthday', models.CharField()),
                ('person_occupation_fr', models.CharField()),
                ('person_gender', models.CharField()),
                ('person_function_latest_fr', models.CharField()),
            ],
            options={
                'db_table': 'data_persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RSGEData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField()),
                ('intitule', models.CharField()),
                ('rubrique', models.CharField()),
                ('chapitre', models.CharField()),
                ('intitule_chapitre', models.CharField()),
                ('intitule_rubrique', models.CharField()),
                ('rubrique_complet', models.CharField()),
                ('chapitre_complet', models.CharField()),
                ('acronym', models.CharField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'data_rsge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RSGEVotingsData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('voting_id', models.CharField()),
                ('voting_external_id', models.CharField()),
                ('voting_date', models.CharField()),
                ('voting_affair_external_id', models.CharField()),
                ('voting_affair_number', models.CharField()),
                ('voting_title_fr', models.CharField()),
                ('voting_url_fr', models.CharField()),
                ('voting_results_yes', models.CharField()),
                ('voting_results_no', models.CharField()),
                ('voting_results_abstention', models.CharField()),
                ('voting_affair_title_fr', models.CharField()),
                ('reference', models.CharField()),
                ('type_vote_label', models.CharField()),
                ('intitule', models.CharField()),
                ('date_d_adoption', models.CharField()),
                ('rubrique', models.CharField()),
                ('chapitre', models.CharField()),
                ('intitule_rubrique', models.CharField()),
                ('intitule_chapitre', models.CharField()),
                ('rubrique_complet', models.CharField()),
                ('chapitre_complet', models.CharField()),
                ('acronym', models.CharField()),
                ('debat_numero', models.SmallIntegerField()),
                ('initial_affair', models.CharField()),
            ],
            options={
                'db_table': 'data_votings_rsge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='votesData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('vote_external_id', models.CharField()),
                ('vote_person_external_id', models.CharField()),
                ('vote_person_fullname', models.CharField()),
                ('vote_voting_external_id', models.CharField()),
                ('vote_label', models.CharField()),
                ('vote_vote_display_fr', models.CharField()),
            ],
            options={
                'db_table': 'data_votes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='RSGEChapter',
        ),
    ]
